language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
#  - "pypy3"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

matrix:
  include:
    - sudo: required
      python: 3.4
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib
      script:
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-manylinux1-wheels.sh
        - ls wheelhouse/
    - sudo: required
      python: 3.4
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib
      script:
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-manylinux1-wheels.sh
        - ls wheelhouse/


before_install:
  - sudo apt-get install cmake
  - "./.travis.sh"

install:
  - pip install .

script:
  - pytest
