os: linux
dist: focal
language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

arch:
  - arm64

env:
  global:
    LIBGIT2: ${TRAVIS_BUILD_DIR}/ci/install
    LD_LIBRARY_PATH: ${LIBGIT2}/lib:${LD_LIBRARY_PATH}

jobs:
  allow_failures:
  - arch: s390x
  include:
  - python: 3.6
    arch: s390x

before_install:
  - sudo apt-get -y install cmake

script:
  - LIBSSH2_VERSION=1.9.0 LIBGIT2_VERSION=1.1.0 /bin/sh build.sh test
