dist: xenial
language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
#  - "pypy3"

env:
  global:
    LIBGIT2: /libgit2/_install/
    LD_LIBRARY_PATH: ~/libgit2/_install/lib


.mixins:
- &docker-job
  dist: xenial
  python: "3.7"
  services:
  - docker
  env:
    DOCKER_IMAGE: quay.io/pypa/manylinux1_x86_64
  script: &docker-script
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-manylinux1-wheels.sh
  - ls wheelhouse/


jobs:
  include:
  - <<: *docker-job
  - <<: *docker-job
    env:
      DOCKER_IMAGE: quay.io/pypa/manylinux1_i686
      PRE_CMD: linux32


before_install:
  - sudo apt-get install cmake
  - "./.travis.sh"

install:
  - pip install .

script:
  - pytest
