dist: xenial
language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"

env:
  global:
    LIBGIT2: ~/libgit2/_install/
    LD_LIBRARY_PATH: ${LIBGIT2}/lib:${LD_LIBRARY_PATH}
    LIBGIT2_VERSION: "0.27"


.mixins:
- &docker-job
  stage: Publish to PyPI (runs only for tagged commits)
  python: "3.7"
  services:
  - docker
  env:
    # DOCKER_IMAGE: quay.io/pypa/manylinux1_x86_64
    DOCKER_IMAGE: pyca/cryptography-manylinux1:x86_64
  install: skip
  script: &docker-script
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-manylinux1-wheels.sh pygit2 "${LIBGIT2_VERSION}"
  - ls wheelhouse/
  before_deploy:
  - mv wheelhouse dist
  - pip install twine
  - twine check dist/*
  deploy:
    provider: pypi
    # `skip-cleanup: true` is required to preserve binary wheels, built
    # inside of manylinux1 docker container during `script` step above.
    skip-cleanup: true
    # `skip-existing: true` is required to skip uploading dists, already
    # present in PYPI instead of failing the whole process.
    # This happens when other CI (AppVeyor etc.) has already uploaded
    # the very same dist (usually sdist).
    skip-existing: true
    user: jdavid
    password:
      # Encrypted with `travis encrypt -r aio-libs/aiohttp --api-endpoint 'https://api.travis-ci.com/'`:
      secure: >-
        TODO: REPLACE THIS WITH AN ENCRYPTED PASSWORD
    # Although Travis CI instructs `setup.py` to build source distribution,
    # which is default value for distribution option (`distribution: sdist`),
    # it will also upload all wheels we've previously built in manylinux1
    # docker container using `twine upload -r pypi dist/*` command.
    # Also since commit https://github.com/travis-ci/dpl/commit/90b5e39
    # it is default that Travis PYPI provider has `skip_upload_docs: true`
    # set by default.
    # Besides above, we don't do cleanup of `dist/*`, because it's being done
    # by Travis CI PYPI deployment provider after upload, unconditionally.
    on:
      tags: true
      all_branches: true


jobs:
  include:
  - <<: *docker-job
    name: >-
      manylinux1: 64-bit
  - <<: *docker-job
    name: >-
      manylinux1: 32-bit
    env:
      # DOCKER_IMAGE: quay.io/pypa/manylinux1_i686
      DOCKER_IMAGE: pyca/cryptography-manylinux1:i686
      PRE_CMD: linux32


before_install:
  - sudo apt-get install cmake
  - ./.travis.sh "${LIBGIT2_VERSION}"

install:
  - pip install .

script:
  - pytest
