dist: xenial
language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"

env:
  global:
    LIBGIT2: ~/libgit2/_install/
    LD_LIBRARY_PATH: ${LIBGIT2}/lib:${LD_LIBRARY_PATH}
    LIBGIT2_VERSION: "0.27"


.mixins:
- &docker-job
  stage: Publish to PyPI (runs only for tagged commits)
  dist: xenial
  python: "3.7"
  services:
  - docker
  env:
    # DOCKER_IMAGE: quay.io/pypa/manylinux1_x86_64
    DOCKER_IMAGE: pyca/cryptography-manylinux1:x86_64
  install: skip
  script: &docker-script
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-manylinux1-wheels.sh pygit2 "${LIBGIT2_VERSION}"
  - ls wheelhouse/


jobs:
  include:
  - <<: *docker-job
    name: >-
      manylinux1: 64-bit
  - <<: *docker-job
    name: >-
      manylinux1: 32-bit
    env:
      # DOCKER_IMAGE: quay.io/pypa/manylinux1_i686
      DOCKER_IMAGE: pyca/cryptography-manylinux1:i686
      PRE_CMD: linux32


before_install:
  - sudo apt-get install cmake
  - ./.travis.sh "${LIBGIT2_VERSION}"

install:
  - pip install .

script:
  - pytest
