name: Linux

on:
  pull_request:
  push:

env:
  LIBGIT2: "${{ github.workspace }}/ci/install"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: [3.6, 3.9, pypy3]
        exclude:
        - os: macos-latest
          python-version: 3.9
        - os: macos-latest
          python-version: pypy3

    steps:
    - name: Checkout pygit2
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build & Test
      run: |
        /bin/sh ci.sh
